# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: "sql ini"

on:
  push: null
  workflow_dispatch: null

permissions: {}

jobs:
  sql_ini:
    runs-on: "ubuntu-latest"
    steps:
      - run: |
          sudo find /etc/mysql/ -type f | sudo xargs -t -L1 -- cat
